# Generated by Django 2.2.1 on 2019-06-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Em destaque?'),
        ),
    ]
