# Generated by Django 2.2.1 on 2019-07-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/imagens', verbose_name='Imagem')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('taxa_inscricao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de inscrição (R$)')),
                ('pdf', models.ImageField(upload_to='eventos/pdfs', verbose_name='Regulamento/Normas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
