# Generated by Django 2.2.1 on 2019-07-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190710_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.IntegerField(choices=[(10, 'Competição'), (20, 'Curso')], default=0, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
