# Generated by Django 2.2.1 on 2019-07-11 19:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190710_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='taxa_inscricao',
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
