# Generated by Django 2.2.1 on 2019-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190711_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricao_data_fim',
            field=models.DateField(default='2019-07-11', verbose_name='Fim das inscrições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao_data_inicio',
            field=models.DateField(default='2019-07-11', verbose_name='Início das inscrições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao_formulario',
            field=models.CharField(default='2019-07-11', max_length=1000, verbose_name='Formulário'),
            preserve_default=False,
        ),
    ]
